
# POST http://127.0.0.1:8000/api/login HTTP/1.1
# content-type: application/json

# {
#     "grant_type": "password",
#     "username": "root",
#     "password": "root",
#     "age": "26",
# }


POST http://127.0.0.1:8000/api/login HTTP/1.1
content-type: application/x-www-form-urlencoded

username=root
&password=root


POST http://127.0.0.1:8000/api/logout HTTP/1.1
content-type: application/json
token: Rr1DMQmzfqtEkIYO7c2NbA6iLFynPTJxx

{
    "username":"root",
    "age":"26"
}

# jwt_token 请求头使用该格式
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJleHBpcmVzIjoxNzI5NjY1MTE1fQ.18n63AugShDuT-opI1qjWQjJNaQh9SbNTbV-KAMiBRc
GET http://127.0.0.1:8000/api/userinfo HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJleHBpcmVzIjoxNzI5NjY1MTE1fQ.18n63AugShDuT-opI1qjWQjJNaQh9SbNTbV-KAMiBRc

{

    "age":"26"
}

POST http://127.0.0.1:8000/api/changepassword HTTP/1.1
content-type: application/json
token:iAwyfx3KSG9PNLjcHOXgqV1oEhFtI7mz

{
    "username":"root",
    "mdf_password":"root",
    "age":"26"
}