name: Deploy to Github Pages
on:
  # # Allows you to run this workflow manually from the Actions tab
  # 该配置需要在默认分支仓库才可触发
  workflow_dispatch:
  workflow_run:
    workflows: ["Build project"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
# 不同 job 之间环境是隔离的
  mkdocs:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   # 只有在 workflow_run 成功时才执行
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'  # 设置 Python 版本      

      - name: Generate official website
        run: |
          pip3 install -r ./pages/requirements.txt
          mkdocs build -f ./pages/userlogin/mkdocs.yml

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site
          retention-days: 1

  # 部署到 GitHub Pages
  deploy:
    env:
      USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
    environment:
        name: github-pages
        # 由 actions/upload-pages-artifact@v3 提供
        url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: mkdocs  # 这个 job 依赖于 mkdocs job 的成功
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: clear github deployment
        run: |
          source project.sh
          project release del_deployment
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

